name: Server coverage

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        java-version: 18
        distribution: 'temurin'
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '>=20.10.0'

    - name: Grant execute permission for gradlew and run Warehouse microservice
      run: | 
        chmod +x gradlew
        ./gradlew run &
      shell: bash

    - name: Start server
      working-directory: server
      run: |
        npm install
        npx ts-node ./src/server &
      shell: bash

    - name: Run Tests websocket
      working-directory: server
      run: |
        sleep 50
        npx jest test/test-server.test.ts --coverage
      shell: bash
      
    - name: Restart Warehouse microservice
      run: |
        gradle --stop
        ./gradlew run &
      shell: bash

    - name: Run Tests checkservice
      working-directory: server
      run: |
        sleep 50
        npx jest test/test-check-service.test.ts --coverage
      shell: bash

