name: Server coverage

#inputs:
 # who-to-greet:  # id of input
  #  description: 'Who to greet'
   # required: true
    #default: 'World'
#outputs:
  #random-number:
    #description: "Random number"
    #value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        java-version: 18
        distribution: 'temurin'
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew

    - name: Run Warehouse Microservice
      run: ./gradlew run &

    - uses: actions/setup-node@v4
      with:
        node-version: '>=20.10.0'
    - name: Start server
      working-directory: server
      run: |
        npm install
        npx ts-node ./src/server &

    - name: Run Tests websocket
      working-directory: server
      run: |
        sleep 50
        npx jest test/test-server.test.ts --coverage
      
    - name: Run Warehouse Microservice
      run: |
        gradle --stop
        ./gradlew run &

    - name: Run Tests checkservice
      working-directory: server
      run: |
        sleep 50
        npx jest test/test-check-service.test.ts --coverage

