name: Server test 

inputs:
  command:  
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for gradlew and run Warehouse microservice
      run: | 
        chmod +x gradlew
        ./gradlew :WarehouseService:run &
      shell: bash

    - name: Start server
      working-directory: server
      run: |
        npm install
        npm start &
      shell: bash

    - name: Start orders-service
      working-directory: orders-service
      run: |
        npm install
        npm start &
      shell: bash

    - name: Start menu-service
      working-directory: menu-service
      run: |
        npm install
        npm start &
      shell: bash

    - name: Run Tests websocket
      working-directory: server
      run: |
        sleep 60
        npm test
      shell: bash