name: Setup sonarcloud workflow

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        java-version: 18
        distribution: 'temurin'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-db: 'Warehouse'
    - uses: actions/setup-node@v4
      with:
        node-version: '>=20.10.0'
