name: Deploy Code Documentation 

on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: write

jobs:
  kotlinDoc:
    name: deploy kotlin doc
    uses: ./.github/workflows/kotlin_doc.yml
  typeDoc:
    name: deploy typescript doc
    uses: ./.github/workflows/typescript_doc.yml
  