name: Deploy documentation

on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: java version
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Generate Javadoc
        run: |
          chmod +x gradlew
          ./gradlew javadoc

      - name: Generate typedoc
        run: |
          declare -a dir=('server' 'manager-application' 'orders-service' 'menu-service' 'customer-application')
          for x in ${dir[@]}; do
            cd ${{ github.workspace }}/$x
            npm install
            npx typedoc --entryPointStrategy expand ./src
          done

      - name: Generate dokka
        run: |
          chmod +x gradlew
          ./gradlew dokkaHtml

      - name: Collect docs
        run: |
          mkdir ${{ github.workspace }}/docs/
          mkdir ${{ github.workspace }}/docs/typedoc/
          declare -a dir=('server' 'manager-application' 'orders-service' 'menu-service' 'customer-application')
          
          for d in ${dir[@]}; do
            mkdir ${{ github.workspace }}/docs/typedoc/$d && cp -r ${{ github.workspace }}/$d/docs/. $_
          done
          mkdir ${{ github.workspace }}/docs/javadoc && cp -r ${{ github.workspace }}/EmployeeApplication/build/docs/javadoc/. $_
          mkdir ${{ github.workspace }}/docs/dokka && cp -r ${{ github.workspace }}/WarehouseService/build/dokka/html/. $_

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          folder: ${{ github.workspace }}/docs/
          branch: report
          target-folder: ./docs