name: Publish Docker image

on:
  #release:
  #  types: [published]
  push:
    branches:
      - develop
jobs:
  deploy:
    strategy:
      matrix:
        #directory: ['WarehouseService', 'menu-service'] #, 'orders-service', 'server', 'manager-application', 'customer-application']
        directory: [ {dir: 'WarehouseService', repo: 'warehouse-service'}, {dir: 'menu-service', repo: 'menu-service'},]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        if: ${{ matrix.directory.dir == 'WarehouseService' }}
        uses: actions/checkout@v4
      - name: WarehouseService shadowJar
        if: ${{ matrix.directory == 'WarehouseService' }}
        run: |
          chmod +x gradlew
          ./gradlew :WarehouseService:shadowJar
        

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.directory.dir }}"
          file: ./Dockerfile
          push: true
          tags: elisaalbertini/${{ matrix.directory.repo }}