name: Publish Docker image

on:
  #release:
  #  types: [published]
  push:
    branches:
      - develop
jobs:
  deploy:
    strategy:
      matrix:
        directory: ['WarehouseService', 'menu-service'] #, 'orders-service', 'server', 'manager-application', 'customer-application']
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
      - name: WarehouseService shadowJar
        run: chmod +x gradlew
      - name: WarehouseService shadowJar pt.2
        run: ./gradlew :WarehouseService:shadowJar

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.directory }}"
          file: ./Dockerfile
          push: true
          tags: elisaalbertini/${{ matrix.directory }}