name: Deploy Javadoc

on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: java version
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install and Build
        run: |
          chmod +x gradlew
          ./gradlew javadoc

      - name: Install and Build server
        working-directory: server
        run: |
          npm install
          npx typedoc --entryPointStrategy expand ./src

      - name: Install and Build menu-service
        working-directory: menu-service
        run: |
          npm install
          npx typedoc --entryPointStrategy expand ./src

      - name: Install and Build orders-service
        working-directory: orders-service
        run: |
          npm install
          npx typedoc --entryPointStrategy expand ./src

      - name: Install and Build manager-application
        working-directory: manager-application
        run: |
          npm install
          npx typedoc --entryPointStrategy expand ./src

      - name: Install and Build
        run: |
          chmod +x gradlew
          ./gradlew dokkaHtml

      - name: collect doc
        run: |
          mkdir ${{ github.workspace }}/docs/
          mkdir ${{ github.workspace }}/docs/typedoc/
          mkdir ${{ github.workspace }}/docs/javadoc && cp -r ${{ github.workspace }}/EmployeeApplication/build/docs/javadoc/. $_
          mkdir ${{ github.workspace }}/docs/dokka && cp -r ${{ github.workspace }}/WarehouseService/build/dokka/html/.
          mkdir ${{ github.workspace }}/docs/typedoc/menu-service && cp -r ${{ github.workspace }}/menu-service/docs/.
          mkdir ${{ github.workspace }}/docs/typedoc/orders-service && cp -r ${{ github.workspace }}/orders-service/docs/.
          mkdir ${{ github.workspace }}/docs/typedoc/manager-application && cp -r ${{ github.workspace }}/manager-application/docs/.
          mkdir ${{ github.workspace }}/docs/typedoc/server && cp -r ${{ github.workspace }}/server/docs/.

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          folder: ${{ github.workspace }}/docs/
          branch: report
          target-folder: ./docs