name: Deploy Javadoc

on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: java version
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install and Build
        run: |
          chmod +x gradlew
          ./gradlew javadoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./EmployeeApplication/build/docs/javadoc
          branch: report
          target-folder: ./docs/javadoc