name: Run menu-service tests

on:
 workflow_call:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: elisaalbertini/paguroDbRepo/.github/setupAction@main
      - name: Run Tests
        working-directory: menu-service
        run: |
          npm install
          npx jest 
        shell: bash