name: Run tests with MongoDB

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-db: 'Warehouse'

      - name: test kotlin
        uses: ./.github/workflows/kotlin_test_pipeline.yml