name: Main project workflow

on:
  workflow_call:
    branches:
      - main
      - develop
jobs:
  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/ktlint_check_pipeline.yml

  tsFormatCheck:
    name: check format ts
    uses: ./.github/workflows/ts_format_check_pipeline.yml

  serverTest:
    needs:
      - tsFormatCheck
    name: test server
    uses: ./.github/workflows/server_test_pipeline.yml

  ordersServiceTest:
    needs:
      - serverTest
      - tsFormatCheck
    name: test orders-service
    uses: ./.github/workflows/orders_service_test_pipeline.yml

  menuServiceTest:
    needs:
      - ordersServiceTest
      - serverTest
      - tsFormatCheck
    name: test menu-service
    uses: ./.github/workflows/menu_service_test_pipeline.yml

  kotlinTest:
    needs:
      - menuServiceTest
      - ordersServiceTest
      - serverTest
      - ktlintCheck
    name: test kotlin with MongoDB
    uses: ./.github/workflows/mongodb_pipeline.yml