name: Main project workflow

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/ktlint_check_pipeline.yml

  tsFormatCheck:
    name: check format ts
    uses: ./.github/workflows/ts_format_check_pipeline.yml

  kotlinTest:
    needs:
      - ktlintCheck
    name: test kotlin with MongoDB
    uses: ./.github/workflows/mongodb_pipeline.yml

  serverTest:
    needs:
      - tsFormatCheck
    name: test server
    uses: ./.github/workflows/server_test_pipeline.yml