name: Setup workflow

setup:
  steps:
    - uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        java-version: 18
        distribution: 'temurin'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-db: 'Warehouse'
    - name: Gradle (build and coverage)
      run: |
        chmod +x gradlew
        ./gradlew jacocoTestReport
