name: Sonarcloud workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  sonarcloud:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.10.0'
      - name: Start server
        working-directory: server
        run: |
          npm install
          npx ts-node ./src/server &

      - name: Run Tests websocket
        working-directory: server
        run: |
          sleep 50
          npx jest test/test-server.test.ts --coverage
        
      - name: Run Warehouse Microservice
        run: |
          gradle --stop
          ./gradlew run &

      - name: Run Tests checkservice
        working-directory: server
        run: |
          sleep 50
          npx jest test/test-check-service.test.ts --coverage