name: Deploy Typedoc
on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: write
jobs:
  build-and-deploy:
    strategy:
      matrix:
        dir: ['server', 'manager-application', 'orders-service', 'menu-service']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        working-directory: ${{ matrix.dir }}
        run: |
          npm install
          npx typedoc --entryPointStrategy expand ./src
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./${{ matrix.dir }}/docs
          branch: report
          target-folder: ./docs/typedoc/${{ matrix.dir }}