name: Run WarehouseService tests

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DistributedCafe/DistributedCafeProject/.github/setupAction@develop

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Test
        run: ./gradlew :WarehouseService:test